### ISSUE TITLE
Plugin cannot connect to kafka on the APE

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#109]
There is an error starting the python plugin in the APE:

```
13-12-24.947 |WARN | [AppInfoParser.java:66] [main] Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=APE1-ANTPAD
        at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
        at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:450)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
        at org.eso.ias.plugin.publisher.impl.KafkaPublisher.start(KafkaPublisher.java:167)
...
13-12-29.960 |WARN | [NetworkClient.java:615] [kafka-producer-network-thread | APE1-ANTPAD] [Producer clientId=APE1-ANTPAD] Connection to node -1 could not be established. Broker may not be available.
```

At first glance the problem is due to registering 2 producer (one for monitor points and another one for the heartbeat) with the same client.id in the same JVM

**Comment by acaproni** [comment]
The HB registers a Kafka producer with `client.id=pluginID`, the same ID used by the `KafkaPlublisher`. This is not allowed by kafka that throws the exception reported above.

Changing the ID of the HB kafka producer let the exception disappear but the connection still fails with the same error
To let the problem disappear I had to turn off the firewall of the virtual machine.

There are 2 issues here:
* the firewall in the vritual machine or the APEs
* the identifier of the client

**Comment by acaproni** [comment]
I close this issue as the firewall will be investigated by IT and the identifier of the consumer is subject of #110
