### ISSUE TITLE
iasDumpKafkaTopic throws exeception when interrupted

### ISSUE THREAD

**Issue by acaproni** [IntegratedAlarmSystem-Group/ias#122]
iasDumpKafkaTopic throws the following exception when interrupted (CTRL+C):

```
Traceback (most recent call last):
  File "/home/acaproni/IasRoot/bin/iasDumpKafkaTopic", line 89, in <module>
    call(cmd)
  File "/opt/anaconda3/lib/python3.5/subprocess.py", line 249, in call
    return p.wait(timeout=timeout)
  File "/opt/anaconda3/lib/python3.5/subprocess.py", line 1399, in wait
    (pid, sts) = self._try_wait(0)
  File "/opt/anaconda3/lib/python3.5/subprocess.py", line 1349, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

CTRL+C is the only way to terminate the iasDumpKafkaTopic so it should cleany terminate and release all the allocated resources (the kafka conenction for instance)

**Comment by acaproni** [comment]
Fixed
