### ISSUE TITLE
JsonReader fails with NPE if ASCE has no templateId defined but instantiated as template

### ISSUE THREAD

**Issue by msekoranja** [IntegratedAlarmSystem-Group/ias#184]
JsonReader fails with NPE if ASCE has no templateId defined but its DASU is instantiated as template. I got the following exception
```
13:03:01.892 |INFO | [Supervisor.scala:103] [main] Building Supervisor [SUPERVISOR_Sensor1] with fullRunningId [(SUPERVISOR_Sensor1:SUPERVISOR)]
java.lang.NullPointerException
	at org.eso.ias.cdb.json.JsonReader.lambda$getDasu$4(JsonReader.java:325)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1577)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:521)
	at org.eso.ias.cdb.json.JsonReader.getDasu(JsonReader.java:325)
	at org.eso.ias.cdb.json.JsonReader.getSupervisor(JsonReader.java:381)
	at org.eso.ias.supervisor.Supervisor.<init>(Supervisor.scala:128)
	at org.eso.ias.supervisor.Supervisor.<init>(Supervisor.scala:278)
	at org.eso.ias.supervisor.Supervisor$.main(Supervisor.scala:610)
	at org.eso.ias.supervisor.Supervisor.main(Supervisor.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.reflect.internal.util.ScalaClassLoader.$anonfun$run$2(ScalaClassLoader.scala:106)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:41)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:37)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.asContext(ScalaClassLoader.scala:132)
	at scala.reflect.internal.util.ScalaClassLoader.run(ScalaClassLoader.scala:106)
	at scala.reflect.internal.util.ScalaClassLoader.run$(ScalaClassLoader.scala:98)
	at scala.reflect.internal.util.ScalaClassLoader$URLClassLoader.run(ScalaClassLoader.scala:132)
	at scala.tools.nsc.CommonRunner.run(ObjectRunner.scala:28)
	at scala.tools.nsc.CommonRunner.run$(ObjectRunner.scala:27)
	at scala.tools.nsc.ObjectRunner$.run(ObjectRunner.scala:45)
	at scala.tools.nsc.CommonRunner.runAndCatch(ObjectRunner.scala:35)
	at scala.tools.nsc.CommonRunner.runAndCatch$(ObjectRunner.scala:34)
	at scala.tools.nsc.ObjectRunner$.runAndCatch(ObjectRunner.scala:45)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:73)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:92)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:103)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:108)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
key line is:
```
at org.eso.ias.cdb.json.JsonReader.lambda$getDasu$4(JsonReader.java:325)
```

that points to (my version of code):

https://github.com/IntegratedAlarmSystem-Group/ias/blob/759e6c07a30b1df5ba64eae0b3560d37ca6e0f40/Cdb/src/main/java/org/eso/ias/cdb/json/JsonReader.java#L325

**Comment by acaproni** [comment]
I reviewed the impleme ntation of templates and found that an ASCE that runs in a templated DASU must have the seme template of the DASU. If the Dasu is not replicated, the ASCE msu have an empty template identifier.
Please, check the [CDB wiki](https://github.com/IntegratedAlarmSystem-Group/ias/wiki/ConfigurationDatabase).

There must be a problem in your CDB (the GUI?).

**Comment by msekoranja** [comment]
Actually I have written JSON CDB by hand and run cdbChecker against it. It
failed with the above exception. Also supervisor (since they share the same
code).
Sure, the CDB is not valid, but at least cdbChecker should not fail and
produce understandable error (reported error was that if failed to read
supervisor).

**Comment by acaproni** [comment]
Agreed: the CdbChecker must report the error instead of failing.

**Comment by acaproni** [comment]
The CdbChecker checks for a missing templateId in the ASCE of a tempated DASU as it should. The errors is due to the fact the taplateId of the ASCE can be empty or null, the latter is not catched properly,

**Comment by acaproni** [comment]
Fixed. The CdbChecker clearly reports the error.
Note that the CdbChecker reports the error (log at ERROR level) plus the exception
